// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drxpnqpawtvhrdjqyqjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyeHBucXBhd3R2aHJkanF5cWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTE0ODgsImV4cCI6MjA3MTc2NzQ4OH0.6TcS5oAvfY_N6pfvul37NuPkCOomkWfWs2Lw7I_21o4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});